
```{r include=FALSE}
library(rmdtools)
library(SeminarMatching)

setwd("D:/libraries/SeminarMatching/semapps/shared/rmd")
db.dir = paste0("../db")
semdb = dbConnect(dbname=paste0(db.dir,"/semDB.sqlite"), drv = SQLite())
seminars = dbGet(semdb,"seminars")


file="studseminfo_round1_en.Rmd"

cat.rmd.params(file)
params = NULL
#cat(paste0(names(res),"=",res, collapse=", "))

today = as.Date(Sys.time())
semester = "SS16"

params = list(
  today = today,
  round1_date = today-1,  
  stud_start_date = today-10,
  round1_done_date = today-1,
  stud.exists = TRUE,
  round2_date = today,
  stud_sems = seminars,
  round2_done_date = today,
  last_latecomer_date = today+5,
  semester = semester
)
copy.into.env(params)
.GlobalEnv$knit_print.Date = function(x,...) {
  restore.point("whisker_print.date")

  format(x, format="%a. %d.%m.%Y")
}
#whisker_print.data.frame = table.knit_print.data.frame

view.rmd(file = file, envir=params,chunks.like.whisker=TRUE)


stop.without.error()
```

<!-- START -->

### Seminar Selection Main Round

Until {{round1_date-1}} you can enter here your preferences over seminars. Please pick all those seminars you would be willing to participate.

Sort the selected seminars according to your preferences (more prefered seminars on top) and **Save your preferences by pressing the button**.

{{actionButton("saveStudprefBtn","Save seminar preferences")}}
              
{{uiOutput("studSemAlert")}}

### Selected Seminars and Preference Order

{{uiOutput("selSemUI")}}

### All seminars

{{uiOutput("allSemUI")}}

Short manual:

+ Press the "+" button to select a seminar from the list of all seminars
+ Press the "x" button to remove a selected seminar.
+ Use the arrow buttons to change your preference order over selected seminars.
+ Press the "Save seminar preferences" button to save your preference list.
