
```{r include=FALSE}
library(rmdtools)
library(SeminarMatching)

setwd("D:/libraries/SeminarMatching/semedit_app/rmd")
db.dir = paste0("../db")
semdb = dbConnect(dbname=paste0(db.dir,"/semDB.sqlite"), drv = SQLite())
seminars = dbGet(semdb,"seminars")


file="studseminfo_post_de.Rmd"

cat.rmd.params(file)
params = NULL
#cat(paste0(names(res),"=",res, collapse=", "))

today = as.Date(Sys.time())
semester = "SS15"

params = list(
  today = today,
  round1_date = today-1,  
  stud_start_date = today-10,
  round1_done_date = today-1,
  stud.exists = TRUE,
  round2_date = today,
  stud_sems = seminars,
  round2_done_date = today,
  last_latecomer_date = today+5,
  semester = semester,
  studmode = "latecomer"
)
copy.into.env(params)
.GlobalEnv$knit_print.Date = function(x,...) {
  restore.point("whisker_print.date")

  format(x, format="%a. %d.%m.%Y")
}
#whisker_print.data.frame = table.knit_print.data.frame

view.rmd(file = file, envir=params,chunks.like.whisker=FALSE)


stop.without.error()
```

<!-- START -->

## WiWi-Seminarmatching, Ulm University {{semester}}

Both seminar matching rounds for {{semester}} are finished.

#< if NROW(stud_sems) == 0
You did not get a seminar slot.
#>
#< if NROW(stud_sems) == 1
You got a slot in the following seminar:
#>
#< if NROW(stud_sems) == 2
You got a slot in the following seminar:
#>
#< if NROW(stud_sems) >= 1
```{r results = 'asis', echo=FALSE}
cat(
  assigned.sems.table(stud_sems=stud_sems,header = c("Seminar","Lecturer"), topic.header = "Topic", topic.choice.label = "Topic selection not active")
)
```
#>
