
```{r include=FALSE}
library(rmdtools)
library(SeminarMatching)

setwd("D:/libraries/SeminarMatching/semapps/shared/rmd")
db.dir = paste0("../db")
semdb = dbConnect(dbname=paste0(db.dir,"/semDB.sqlite"), drv = SQLite())
seminars = dbGet(semdb,"seminars")


file="studseminfo_round1_de.Rmd"

cat.rmd.params(file)
params = NULL
#cat(paste0(names(res),"=",res, collapse=", "))

today = as.Date(Sys.time())
semester = "SS16"

params = list(
  today = today,
  round1_date = today-1,  
  stud_start_date = today-10,
  round1_done_date = today-1,
  stud.exists = TRUE,
  round2_date = today,
  stud_sems = seminars,
  round2_done_date = today,
  last_latecomer_date = today+5,
  semester = semester
)
copy.into.env(params)
.GlobalEnv$knit_print.Date = function(x,...) {
  restore.point("whisker_print.date")

  format(x, format="%a. %d.%m.%Y")
}
#whisker_print.data.frame = table.knit_print.data.frame

view.rmd(file = file, envir=params,chunks.like.whisker=TRUE)


stop.without.error()
```

<!-- START -->

### Seminarauswahl Hauptrunde

Sie können hier noch bis zum {{round1_date-1}} Ihre Präferenzliste über Seminare angeben. Wählen Sie bitte aus der Liste aller Seminare diejenigen und nur diejenigen Seminare aus, an denen Sie teilnehmen würden, wenn Sie einen Platz erhalten.

Sortieren Sie dann die ausgewählten Seminare gemäß Ihrer Wunschreihenfolge
(bevorzugte Seminare weiter oben) und **speichern Sie dann per Knopfdruck ihre Präferenzen**.

{{actionButton("saveStudprefBtn","Präferenzliste speichern")}}
              
{{uiOutput("studSemAlert")}}

### Ausgewählten Seminare und Rangfolge

{{uiOutput("selSemUI")}}

### Alle angebotenen Seminare

{{uiOutput("allSemUI")}}

Kurzanleitung:

+ Klicken Sie auf den "+" Knopf um ein Seminar aus der Liste aller Seminare auszuwählen.
+ Mit dem "x" Knopf können Sie ein ausgewähltes Seminar wieder entfernen.
+ Mit den Pfeilknöpfen, können Sie die Reihenfolge der Seminare in Ihrer Präferenzliste ändern.
+ Drücken Sie auf den Knopf "Präferenzliste speichern" um Ihre Seminarpräferenzen abzuspeichern.

