
```{r include=FALSE}
library(rmdtools)
library(SeminarMatching)

setwd("D:/libraries/SeminarMatching/semapps/shared/rmd")
db.dir = paste0("../db")
semdb = dbConnect(dbname=paste0(db.dir,"/semDB.sqlite"), drv = SQLite())
seminars = dbGet(semdb,"seminars")


file="studseminfo_round1_de.Rmd"

cat.rmd.params(file)
params = NULL
#cat(paste0(names(res),"=",res, collapse=", "))

today = as.Date(Sys.time())
semester = "SS16"

params = list(
  today = today,
  round1_date = today-1,  
  stud_start_date = today-10,
  round1_done_date = today-1,
  stud.exists = TRUE,
  round2_date = today,
  stud_sems = seminars,
  round2_done_date = today,
  last_latecomer_date = today+5,
  semester = semester
)
copy.into.env(params)
.GlobalEnv$knit_print.Date = function(x,...) {
  restore.point("whisker_print.date")

  format(x, format="%a. %d.%m.%Y")
}
#whisker_print.data.frame = table.knit_print.data.frame

view.rmd(file = file, envir=params,chunks.like.whisker=TRUE)


stop.without.error()
```

<!-- START -->

### Seminarauswahl Hauptrunde

Sie können hier noch bis zum {{round1_date-1}} Ihre Präferenzliste über Seminare angeben. Wählen Sie bitte aus der Liste aller Seminare diejenigen und nur diejenigen Seminare aus, an denen Sie teilnehmen würden, wenn Sie einen Platz erhalten.

Sortieren Sie dann die ausgewählten Seminare gemäß Ihrer Wunschreihenfolge
(bevorzugte Seminare weiter oben) und **speichern Sie dann per Knopfdruck ihre Präferenzen**.


#< note "Details zur Seminarplatzvergabe"

- Sie können so viele Seminare in Ihre Präferenzliste aufnehmen, wie Sie möchten.

- Sie bekommen Hauptvergaberunde maximal einen Seminarplatz hieraus zugeteilt. Wenn Sie an zwei Seminaren teilnehmen möchten, müssen Sie auch an der zweiten Vergaberunde im Anschluss teilnehmen.

- Sie sollten alle Seminare und nur diese Seminare aufnehmen, an denen Sie wirklich teilnehmen würden, wenn Sie einen Seminarplatz erhalten.

- Wenn Sie einen Seminarplatz erhalten und später doch nicht teilnehmen, können Sie ggf. einen Malus bei zukünftigen Seminarvergaben erhalten.

- Die Seminarplätze werden gemäß des studentenoptimalen <a href="https://en.wikipedia.org/wiki/Stable_marriage_problem" target="_blank">Gale-Shapley Algorithmus</a> zugeteilt.

- Dies bedeutet, es ist in Ihrem besten Interesse
(eine schwach dominante Strategie) Ihre
Präferenzreihenfolge über die Seminare
wahrheitsgetreu anzugeben.

- Dies ist anders als z. B. bei der Studienplatzvergabe der ZVS, wo es z. B. Sinn machen könnte seine zweite Wahl aus strategischen Gründen auf Platz 1 zu setzen.

- Bei unserem Vergabemechanismus ist für Sie niemals vorteilhaft, Ihre Präferenzen aus strategischen Gründen falsch anzugeben.

- Die Zuteilung der Seminare erfolgt automatisch am {{round1_date}}. Sie sehen hiernach ob und welchen Seminarplatz Sie erhalten haben.
#> end note


### Ausgewählten Seminare und Rangfolge

{{uiOutput("selSemUI")}}

{{checkboxInput("partInRound2Checkbox","Ich möchte an zwei Seminaren teilnehmen und diese Präferenzen für die zweite Runde übernehmen. (Präferenzen können später noch angepasst werden.)",value = FALSE)}}

{{actionButton("saveStudprefBtn","Präferenzliste speichern")}}
{{bsAlert("saveStudprefAlert")}}

### Alle angebotenen Seminare

{{uiOutput("allSemUI")}}




