
```{r include=FALSE}
library(rmdtools)
library(SeminarMatching)

setwd("D:/libraries/SeminarMatching/semapps/shared/rmd")
db.dir = paste0("../db")
semdb = dbConnect(dbname=paste0(db.dir,"/semDB.sqlite"), drv = SQLite())
seminars = dbGet(semdb,"seminars")


file="studseminfo_round2_de.Rmd"

cat.rmd.params(file)
params = NULL
#cat(paste0(names(res),"=",res, collapse=", "))

today = as.Date(Sys.time())
semester = "SS16"

params = list(
  today = today,
  round1_date = today-1,  
  stud_start_date = today-10,
  round1_done_date = today-1,
  stud.exists = TRUE,
  round2_date = today,
  stud_sems = seminars,
  round2_done_date = today,
  last_latecomer_date = today+5,
  semester = semester
)
copy.into.env(params)
.GlobalEnv$knit_print.Date = function(x,...) {
  restore.point("whisker_print.date")

  format(x, format="%a. %d.%m.%Y")
}
#whisker_print.data.frame = table.knit_print.data.frame

view.rmd(file = file, envir=params,chunks.like.whisker=FALSE)


stop.without.error()
```

<!-- START -->

### Seminarauswahl 2. Runde

#< if NROW(stud_sems)>0
Sie haben bereits einen Platz in folgendem Seminar erhalten:

**{{paste0(stud_sems$semname, collape=", ")}}**

Falls Sie an zwei Seminaren teilnehmen möchten, können Sie hier noch bis zum Ihre {{round2_date-1}} Präferenzen für Ihr zweites Seminar angeben.
#>

#< if NROW(stud_sems)==0
Sie haben leider in der ersten Runde keinen Seminarplatz erhalten.

Sie können hier noch bis zum {{round2_date-1}} im Reiter `Seminarwahl` Präferenzen für die zweite Vergaberunde angeben.
#>


Wählen Sie bitte aus der Liste aller Seminare diejenigen und nur diejenigen Seminare aus, an denen Sie noch teilnehmen würden, wenn Sie einen Platz erhalten. (Die grau hinterlegte Seminare sind in der ersten Runde bereits gefüllt wurden. Nehmen Sie auch die grauen Seminare auf, an denen Sie teilnehmen würden. Sollte in einem solchen Seminar doch noch jemand abspringen, sieht der Dozent, dass Sie an dem Seminar teilnehmen würden, und kann Ihnen ggf. noch einen Platz anbieten. Die Chance in der automatischen Vergabe noch einen freien Platz in einem weißen Seminar zu bekommen, wird nicht dadurch beeinflusst ob und wo in Ihrer Liste sie die grauen Seminare gerankt haben.)

Sortieren Sie dann die ausgewählten Seminare gemäß Ihrer Wunschreihenfolge
(bevorzugte Seminare weiter oben) und **speichern Sie dann per Knopfdruck ihre Präferenzen**.

{{actionButton("saveStudprefBtn","Präferenzliste speichern")}}

{{uiOutput("studSemAlert")}}

### Ausgewählten Seminare und Rangfolge

{{uiOutput("selSemUI")}}

{{actionButton("copyStudprefBtn","Präferenzliste aus Hauptrunde übernehmen und speichern.")}}
### Alle angebotenen Seminare

{{uiOutput("allSemUI")}}

Kurzanleitung:

+ Klicken Sie auf den "+" Knopf um ein Seminar aus der Liste aller Seminare auszuwählen.
+ Mit dem "x" Knopf können Sie ein ausgewähltes Seminar wieder entfernen.
+ Mit den Pfeilknöpfen, können Sie die Reihenfolge der Seminare in Ihrer Präferenzliste ändern.
+ Drücken Sie auf den Knopf "Präferenzliste speichern" um Ihre Seminarpräferenzen abzuspeichern.
