
```{r include=FALSE}
library(rmdtools)
library(SeminarMatching)

setwd("D:/libraries/SeminarMatching/semedit_app/rmd")
db.dir = paste0("../db")
semdb = dbConnect(dbname=paste0(db.dir,"/semDB.sqlite"), drv = SQLite())
seminars = dbGet(semdb,"seminars")


file="studseminfo_matchingnote_de.Rmd"

cat.rmd.params(file)
params = NULL
#cat(paste0(names(res),"=",res, collapse=", "))

today = as.Date(Sys.time())
semester = "SS15"

params = list(
  today = today,
  round1_date = today-1,  
  stud_start_date = today-10,
  round1_done_date = today-1,
  stud.exists = TRUE,
  round2_date = today,
  has_round1_seminar = TRUE,
  round1_seminar = seminars[1,],
  round2_done_date = today,
  has_round2_seminar = !TRUE,
  round2_seminar = seminars[2,],
  last_latecomer_date = today+5,
  semester = semester,
  studmode = "latecomer"
)
copy.into.env(params)
.GlobalEnv$knit_print.Date = function(x,...) {
  restore.point("whisker_print.date")

  format(x, format="%a. %d.%m.%Y")
}
#whisker_print.data.frame = table.knit_print.data.frame

view.rmd(file = file, envir=params,chunks.like.whisker=FALSE)


stop.without.error()
```

<!-- START -->

#< note "Details zur Seminarplatzvergabe"
- Sie können so viele Seminare in Ihre Präferenzliste aufnehmen, wie Sie möchten. Sie bekommen in jeder Vergaberunde maximal einen Seminarplatz hieraus zugeteilt.

- Sie sollten alle Seminare und nur diese Seminare aufnehmen, an denen Sie wirklich teilnehmen würden, wenn Sie einen Seminarplatz erhalten.

- Wenn Sie einen Seminarplatz erhalten und später doch nicht teilnehmen, können Sie ggf. einen Malus bei zukünftigen Seminarvergaben erhalten.

- Die Seminarplätze werden gemäß des studentenoptimalen <a href="https://en.wikipedia.org/wiki/Stable_marriage_problem" target="_blank">Gale-Shapley Algorithmus</a> zugeteilt.

- Dies bedeutet, es ist in Ihrem besten Interesse
(eine schwach dominante Strategie) Ihre
Präferenzreihenfolge über die Seminare
wahrheitsgetreu anzugeben.

- Dies ist anders als z. B. bei der Studienplatzvergabe der ZVS, wo es z. B. Sinn machen könnte seine zweite Wahl aus strategischen Gründen auf Platz 1 zu setzen.

- Bei unserem Vergabemechanismus ist für Sie niemals vorteilhaft, Ihre Präferenzen aus strategischen Gründen falsch anzugeben.
#> end note
